WITH source_data AS (
    SELECT 
        {{ dbt_utils.generate_surrogate_key([
            'Age', 
            'Gender',
            'Workout_Type',
            'meal_name',
            '`Name of Exercise`',
            'Sets',
            'Reps',
            'serving_size_g'
        ]) }} AS lifestyle_key,
        CAST(Age AS FLOAT64) AS Edad,
        CAST(Gender AS STRING) AS Genero,
        `Weight _kg_` AS Peso,
        `Height _m_` AS Altura,
        Max_BPM AS Maximo_Pulsaciones,
        Avg_BPM AS Promedio_Pulsaciones,
        Resting_BPM AS Pulsaciones_Reposo,
        `Session_Duration _hours_` AS Duracion_Sesion_Horas,
        Calories_Burned AS Calorias_Quemadas,
        Workout_Type AS Tipo_Entrenamiento,
        Fat_Percentage AS Porcentaje_Grasa,
        `Water_Intake _liters_` AS Ingesta_Agua_Litros,
        `Workout_Frequency _days_week_` AS Frecuencia_Entrenamiento_Por_Dia,
        Experience_Level AS Nivel_Experiencia,
        BMI AS Indice_Masa_Corporal,
        `Daily meals frequency` AS Frecuencia_Comidas_Diarias,
        `Physical exercise` AS Ejercicio_Fisico, 
        Carbs AS Carbohidratos,
        Proteins AS Proteinas,
        Fats AS Grasas,
        Calories AS Calorias,
        meal_name AS Nombre_Comida,
        meal_type AS Tipo_Comida,
        diet_type AS Tipo_Dieta,
        sugar_g AS Azucar_Gramos,
        sodium_mg AS Sodio_Miligramos,
        cholesterol_mg AS Colesterol_Miligramos,
        serving_size_g AS Tamano_Porcion_Gramos,
        cooking_method AS Metodo_Coccion,
        prep_time_min AS Tiempo_Preparacion_Minutos,
        cook_time_min AS Tiempo_Coccion_Minutos,
        rating AS Calificacion,
        `Name of Exercise` AS Nombre_Ejercicio,
        Sets AS Series,
        Reps AS Repeticiones,
        Benefit AS Beneficios,
        `Burns Calories _per 30 min_` AS Quema_Calorias_por_30_min, 
        `Target Muscle Group` AS Grupo_Muscular_Objetivo, 
        `Equipment Needed` AS Equipo_Necesario, 
        `Difficulty Level` AS Nivel_Dificultad, 
        `Body Part` AS Parte_Cuerpo, 
        `Type of Muscle` AS Tipo_Musculo, 
        Workout AS Entrenamiento,
        BMI_calc AS IMC_Calculado,
        cal_from_macros AS Calorias_de_Macronutrientes,
        pct_carbs AS Porcentaje_Carbohidratos,
        protein_per_kg AS Proteina_por_kg,
        pct_HRR AS Porcentaje_Reserva_FC,
        pct_maxHR AS Porcentaje_Maximo_FC,
        cal_balance AS Balance_Calorico,
        lean_mass_kg AS Masa_Magra_kg,
        expected_burn AS Quema_Esperada,
        `Burns Calories _per 30 min__bc` AS Quema_Calorias_por_30_min_bc, 
        Burns_Calories_Bin AS Quema_Calorias_Bin
    FROM 
        {{ source('GCP Dataset', 'full_data') }}
)

SELECT *
FROM source_data